description: Pipeline for parsing postfix mail.log. Requires the geoip plugin.
processors:
- drop:
    description: Drop if the Message comes from HAPROXY Heartbeat
    if: ctx?.message =~ /mx-lb1.internal.cloudapp.net/ || ctx?.message =~ /WHITELISTED
      \[[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(:[0-9]+)?\]/ || ctx?.message =~ /CONNECT from
      \[[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(:[0-9]+)?\]/
- rename:
    field: program
    ignore_missing: true
    target_field: process.name
- rename:
    field: pid
    ignore_missing: true
    target_field: process.pid
- grok:
    field: message
    ignore_failure: false
    ignore_missing: false
    pattern_definitions:
      POSTFIX_PREFIX: '%{SYSLOGTIMESTAMP:timestamp} %{SYSLOGHOST:host.hostname} %{SYSLOGPROG}\[%{POSINT:process.pid:long}\]'
    patterns:
    - '^%{POSTFIX_PREFIX}: %{BASE16NUM:postfix.mail.queue_id}: %{DATA:message}$'
    - '^%{POSTFIX_PREFIX}: %{DATA:message}$'
- grok:
    field: message
    ignore_failure: false
    ignore_missing: false
    pattern_definitions:
      POSTFIX_HOST: '%{DATA:postfix.mail.remote_host} ?\[%{DATA:postfix.mail.remote_address}\]'
    patterns:
    - ^client=%{POSTFIX_HOST}, sasl_method=LOGIN, sasl_username=%{DATA:postfix.mail.login_username}$
    - '^%{LOGLEVEL}: Recipient address rate limit exceeded: %{DATA:message} from %{POSTFIX_HOST}
      for service smtp$'
    - ^from=<%{DATA:postfix.mail.from}>, size=%{POSINT:postfix.mail.size:long}, nrcpt=%{POSINT:postfix.mail.nrcpt:int}
    - ^to=<%{DATA:postfix.mail.to}>.+ relay=%{POSTFIX_HOST}.+ status=%{DATA:postfix.mail.status}.\(
    - ^to=<%{DATA:postfix.mail.to}>.+ relay=%{HOSTNAME}.+ status=%{DATA:postfix.mail.status}.\(
    - ^(connect|disconnect|lost connection after CONNECT) from %{POSTFIX_HOST}$
    - '^login: %{POSTFIX_HOST} %{USERNAME:login.username} %{DATA:login.method} %{DATA:message}$'
    - '^%{LOGLEVEL}: %{DATA:message}$'
    - ^message-id=<%{DATA:message_id} ?%{DATA:message}>$
    - ^%{GREEDYDATA:message}$
- date:
    field: timestamp
    formats:
    - MMM  d HH:mm:ss
    - MMM dd HH:mm:ss
    - MMM d HH:mm:ss
    - ISO8601
    ignore_failure: false
    locale: en-US
    target_field: '@timestamp'
    timezone: '+0000'
- remove:
    field: timestamp
    ignore_missing: true
- geoip:
    field: postfix.mail.remote_address
    ignore_failure: true
    ignore_missing: true
    target_field: source.geo
- geoip:
    database_file: GeoLite2-ASN.mmdb
    field: postfix.mail.remote_address
    ignore_missing: true
    properties:
    - asn
    - organization_name
    target_field: source.as
